#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # Disable vimfiler in welcome window to speed up start up time
    enable_vimfiler_welcome = 0
    # Default GUI font
    guifont = 'SauceCodePro Nerd Font Mono'
    # Custom GUI font
    # guifont = 'Droid Sans Mono for Powerline Plus Nerd File Types Mono'
    # Call custom bootstrap function
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

# Enable denite layer for fuzzy finding; unite is obsolete.
[[layers]]
name = 'denite'

# Enable c/c++/objective-c layer
[[layers]]
name = 'lang#c'

# Enable Golang layer
[[layers]]
name = 'lang#go'

# Enable Python layer
[[layers]]
name = 'lang#python'
format-on-save = 1

# Enable LSP layer
[[layers]]
name = 'lsp'
filetypes = [ "python" ]
